/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.JOptionPane;
/**
 *
 * @author INFINIX
 */
public class Soal02 extends javax.swing.JFrame {
    private int countdownTime = 10; // Nilai countdown tetap
    private Timer timer;
    private boolean isStarted = false;

    public Soal02() {
        initComponents();
        initTimer();
    }

    private void initTimer() {
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (isStarted) { //emeriksa apakah hitung mundur telah dimulai
                    countdownTime--;
                    if (countdownTime >= 0) {
                        updateCountdownLabel();
                    } else {
                        timer.stop();
                        countdownTime = 0;
                        updateCountdownLabel();
                        isStarted = false; // Memberhentikan hitung mundur setelah selesai
                        JOptionPane.showMessageDialog(null, "Hitung Mundur Selesai", 
                                "Info", JOptionPane.INFORMATION_MESSAGE);

                        // Munculkan kotak dialog untuk memasukkan angka baru
                        String newTime = JOptionPane.showInputDialog(null, "Masukkan angka baru:",
                                "Input", JOptionPane.QUESTION_MESSAGE);
                        try {
                            countdownTime = Integer.parseInt(newTime);
                            updateCountdownLabel();
                        } catch (NumberFormatException ex) {
                            countdownLabel.setText("Invalid Input");
                        }
                    }
                }
            }
        });
    }

    private void updateCountdownLabel() {
        countdownLabel.setText(String.valueOf(countdownTime));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        countdownLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        countdownLabel.setFont(new java.awt.Font("Arial Narrow", 1, 48)); // NOI18N
        countdownLabel.setForeground(new java.awt.Color(255, 255, 255));
        countdownLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countdownLabel.setText("10");
        getContentPane().add(countdownLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 60, 50));

        startButton.setText("start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        stopButton.setText("stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stopButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DC0.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        timer.stop();
        isStarted = false; // Memberhentikan hitung mundur jika tombol berhenti diklik
    }//GEN-LAST:event_stopButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
       if (!isStarted) { // Memulai hitung mundur hanya jika belum dimulai
            isStarted = true;
            timer.start();
        }
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Soal02 app = new Soal02();
                app.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel countdownLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables
}